source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

def shared_pods 
  pod 'SnapKit', '~> 3.0.2'
  pod 'Watchdog', '~> 3.0'
end

target 'arek' do
  shared_pods 
end

target 'arekTests' do
  shared_pods
end
